#!/usr/bin/env bash

# make `direnv` silent
export DIRENV_LOG_FORMAT=$'\e[32m\e[1m[INFO]\e[0m\e[32m direnv: %s\e[0m '

# Ensure this script has not been modified
_check_sha1 "${XDG_CONFIG_HOME:-${HOME}/.config}/direnv/direnvrc" || exit 1

dotenv_if_exists "${PWD}/.env.secrets"

# vim: ft=bash