#!/usr/bin/env bash
# shellcheck disable=SC2155

source_up_if_exists

# Gitlab Token
if ! is_yubikey_plugged; then
  _log "WARNING" "Secret not loaded in environment"
else
  export GITLAB_HOST="framagit.org"
  export GITLAB_TOKEN="$(kp show /informatique/gitlab/framagit -a "ACCESS_TOKEN:git-deploy")"
fi

# vim: ft=bash
